name: Go mod update

env:
  GO_VERSION: 1.18

on:
  workflow_dispatch:
  schedule:
    - cron: "5 14 * * 1"

jobs:

  dep_update:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ env.GO_VERSION }}
  
    - shell: bash
      env:
        ROOT_CLIENT_PEM: ${{ secrets.ROOT_CLIENT_PEM }}
        ROOT_CLIENT_KEY_PEM: ${{ secrets.ROOT_CLIENT_KEY_PEM }}
        CA_CSR: ${{ secrets.CA_CSR }}
        CA_KEY_PEM: ${{ secrets.CA_KEY_PEM }}
        CA_PEM: ${{ secrets.CA_PEM }}
        NOBODY_CLIENT_PEM: ${{ secrets.NOBODY_CLIENT_PEM }}
        NOBODY_CLIENT_KEY_PEM: ${{ secrets.NOBODY_CLIENT_KEY_PEM }}
        
      run: |
        mkdir -p ~/.godcls
        echo "$ROOT_CLIENT_PEM" | base64 -d > ~/.godcls/root-client.pem
        echo "$ROOT_CLIENT_KEY_PEM" | base64 -d > ~/.godcls/root-client-key.pem
        echo "$CA_CSR" | base64 -d > ~/.godcls/ca.csr
        echo "$CA_PEM" | base64 -d > ~/.godcls/ca.pem
        echo "$CA_KEY_PEM" | base64 -d > ~/.godcls/ca-key.pem
        echo "$NOBODY_CLIENT_PEM" | base64 -d > ~/.godcls/nobody-client.pem
        echo "$NOBODY_CLIENT_KEY_PEM" | base64 -d > ~/.godcls/nobody-client-key.pem

    - name: Update minor dependencies
      run: go get -t -u ./...

    - name: Tidy
      run: go mod tidy

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Create PR
      uses: peter-evans/create-pull-request@v4.0.4
      with:
        title: "update package dependencies & tidy"
        body: |
          this is an automagic PR, and will likely be automated in the future.

          until then, happy approving.
        branch: "dep-update"
        commit-message: |
          this is an automagic PR, and will likely be automated in the future.

          until then, happy approving.
        author: "git bot <gitbot@joshuaejs.me>"
        delete-branch:
          true
        reviewers: |
          joshuaejs
